"""Geographic adaptation and agent cloning schemas.

Defines persona configuration, preview types, and clone entities
used by the AgentCloneManager and PersonaBuilder to create and
manage personalized sales agent clones.
"""

from __future__ import annotations

import enum
from datetime import datetime
from typing import Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field


class PersonaDimension(str, enum.Enum):
    """Axes of persona customization.

    Each dimension is a continuum from 0.0 to 1.0:
    - formal_casual: 0.0 = very casual, 1.0 = very formal
    - concise_detailed: 0.0 = concise, 1.0 = detailed
    - technical_business: 0.0 = business-focused, 1.0 = technical
    - proactive_reactive: 0.0 = reactive, 1.0 = proactive
    """

    formal_casual = "formal_casual"
    concise_detailed = "concise_detailed"
    technical_business = "technical_business"
    proactive_reactive = "proactive_reactive"


class PersonaConfig(BaseModel):
    """Configuration for a clone's communication persona.

    Defines the personality dimensions, geographic region,
    and any custom instructions that shape how this clone
    communicates. Core sales methodology is NOT affected
    by persona settings -- only communication style.
    """

    model_config = ConfigDict(from_attributes=True)

    clone_id: str = Field(
        ...,
        description="Clone this persona belongs to",
    )
    tenant_id: str = Field(
        ...,
        description="Tenant identifier",
    )
    owner_id: str = Field(
        ...,
        description="Sales rep who owns this persona/clone",
    )
    dimensions: Dict[PersonaDimension, float] = Field(
        default_factory=lambda: {
            PersonaDimension.formal_casual: 0.5,
            PersonaDimension.concise_detailed: 0.5,
            PersonaDimension.technical_business: 0.5,
            PersonaDimension.proactive_reactive: 0.5,
        },
        description="Personality dimension values (0.0-1.0 for each axis)",
    )
    region: Optional[str] = Field(
        default=None,
        description="Geographic region for style adaptation: apac, emea, americas",
    )
    custom_instructions: Optional[str] = Field(
        default=None,
        description="Free-form instructions for additional persona customization",
    )


class PersonaPreview(BaseModel):
    """Preview of how a persona will behave before deployment.

    Generated by the PersonaBuilder to let sales reps evaluate
    the clone's communication style before activating it.
    """

    model_config = ConfigDict(from_attributes=True)

    persona: PersonaConfig = Field(
        ...,
        description="The persona configuration being previewed",
    )
    sample_email: str = Field(
        ...,
        description="Sample email written in this persona's style",
    )
    sample_chat: str = Field(
        ...,
        description="Sample chat message written in this persona's style",
    )
    persona_summary: str = Field(
        ...,
        description="Human-readable summary of the persona's characteristics",
    )


class GeographicProfile(BaseModel):
    """Structured profile for a geographic region.

    Contains communication defaults and metadata used by the
    GeographicAdapter to generate region-appropriate prompt sections.
    """

    model_config = ConfigDict(from_attributes=True)

    code: str = Field(
        ...,
        description="Region code: apac, emea, americas",
    )
    name: str = Field(
        ...,
        description="Human-readable region name",
    )
    communication_style: str = Field(
        ...,
        description="Summary of the region's preferred communication approach",
    )
    cultural_notes: List[str] = Field(
        default_factory=list,
        description="Key cultural considerations for sales engagement",
    )
    formality_default: float = Field(
        default=0.5,
        ge=0.0,
        le=1.0,
        description="Default formality level for this region (0.0=casual, 1.0=formal)",
    )


class Clone(BaseModel):
    """A sales agent clone with persona customization.

    Clones share product knowledge, sales methodologies,
    and pattern insights across the tenant. Each clone has
    a unique persona that affects communication style only.
    """

    model_config = ConfigDict(from_attributes=True)

    clone_id: str = Field(
        ...,
        description="Unique clone identifier",
    )
    tenant_id: str = Field(
        ...,
        description="Tenant identifier",
    )
    clone_name: str = Field(
        ...,
        description="Display name for this clone",
    )
    owner_id: str = Field(
        ...,
        description="Sales rep who owns this clone",
    )
    persona: PersonaConfig = Field(
        ...,
        description="Persona configuration for this clone",
    )
    created_at: datetime = Field(
        ...,
        description="When the clone was created (UTC)",
    )
    active: bool = Field(
        default=True,
        description="Whether the clone is currently active",
    )
